### ISSUE TITLE
Правки для 2.18

### ISSUE THREAD

**Issue by Yobas** [Relicta-Team/ReSDK_A3.vr#522]
Список на исправление:
- [x] Форматированный вывод информации о пользователе
- [x] Исправление ошибки форматирования в debugvars
- [x] Тестирование прода с новой версией на сервере (возможно потребует #494)
  - [x] null-значения в словаре yaml парсера при компиляции вызывают ошибку
  - [x] ~~ВПН не даёт зайти на сервер~~ goobdyedpi youtube_all (thanks @7kaiden7)
  - [x] Нет сообщения о тревоге на новой карте (поправит @Italovich-Relicta)
  - [x] Отбой сразу можно нажать. Нужна задержка. (дам @Italovich-Relicta правку)
  - [x] Делей на кнопку тревоги нужен. (дам @Italovich-Relicta правку)
  - [x] Не пишет сообщение про смену лица в лобби (не воспроизводится. проверить на проде)
  - [x] Исправить баг перешагивание + комбат
- [x] #517 

Новый функционал:
- [x] Толстые линии при отрсисовке чанков
- [x] ~~Толстые линии при отрисовке нагрузочных зон~~
- [x] Толстые линии при подключении источников, связях между источниками
- [x] screenPosToWorldPoint ~~(условная компиляция во всех местах, флаг `USE_NEW_MOUSE_TO_SCENE_FUNCTION`)~~
- [x] заменить setPhysicsCollisionFlag 
- [x] обновить виртуалку в RBuilder до новой версии
- [x] Задействовать get3DENLayer (#225)
- [x] Диапазоны лута (#521) и указание дочерних типов с помощью опции `all_types_of`
- [x] #515 
- [x] #519

**Comment by Yobas** [comment]
Все работы по восстановлению функционала готовы.
Новые фишки освоены и реализованы. Остаётся только проверить сборку в работе

**Comment by Yobas** [comment]
@Italovich-Relicta не забудь выпустить пулл реквест с правками к запуску...
